Forward command
cheetah-game-platform/platform pull request #243
Opened 2022-11-01 12:05 UTC by zakharovvi

Closes #120

2022-11-02 03:36 UTC, avkviring commented on modules/matches/Realtime/common/Common/src/commands/c2s.rs
> +	Forwarded(Box<ForwardedCommand>),
Теперь  я понял зачем Box, какие варианты для его избавления, каждый из них не идеален, и не лучше текущего:

1. Подтверждать команды через идентификатор, а не пересылая их полностью. Из плюсов - меньше сетевой трафик, из минусов их какое-то время надо хранить на сервере. 
2. Использовать серию команд - типа:
   C2S::StartAllowedBlock(user, N), а далее просто вызываем N команд из C2S. При этом надо будет использовать канал с гарантие доставки, но это не проблема, так как плагин и сервер это один pod в kubernetes.

2022-11-02 03:42 UTC, avkviring approved these changes

2022-11-02 18:54 UTC, zakharovvi commented on modules/matches/Realtime/common/Common/src/commands/c2s.rs
> +	Forwarded(Box<ForwardedCommand>),
обсудили и решили оставить как есть

2022-11-03 03:21 UTC, avkviring commented on modules/matches/Realtime/server/src/room/forward.rs
> +					self.forwarded_command_configs.contains(&ForwardedCommandConfig {
Тут неплохо бы добавить еще проверку только на FieldId без ObjectTemlateId

2022-11-03 03:23 UTC, avkviring commented on modules/matches/Realtime/server/src/room/forward.rs
> +		self.send_to_members(
Фильтр по группе работает на совпадение хотя бы одного бита, то есть здесь отправка не супер пользователям, а всем. Надо использовать фильтр |_user| и в нем прописать условие

2022-11-03 03:25 UTC, avkviring reviewed
Есть одно критичное замечание

2022-11-03 08:43 UTC, zakharovvi commented on modules/matches/Realtime/client/rust/Realtime/src/ffi/mod.rs
> +pub struct ForwardedCommandFFI {
todo: command_type_id и field_type интом

2022-11-04 02:59 UTC, avkviring requested changes

2022-11-04 02:59 UTC, avkviring commented on modules/matches/Realtime/client/rust/Realtime/src/ffi/mod.rs
> +	has_field_type: bool,
Это вроде как полностью определяется из command_type_id

2022-11-04 02:59 UTC, avkviring commented on modules/matches/Realtime/client/rust/Realtime/src/ffi/mod.rs
> +pub struct ForwardedCommandFFI {
Надо еще добавить три поля - binary_value, double_value, long_value - плагину надо знать данные команды, а не просто сам факт команды
При этом для CAS команда - надо long_value[2], binary_value[2]

2022-11-05 03:12 UTC, avkviring approved these changes

2022-11-05 03:13 UTC, avkviring approved these changes

2022-11-05 03:14 UTC, merged