Доработки UserStore
cheetah-game-platform/platform pull request #92
Opened 2022-08-05 15:38 UTC by flaamjab

2022-08-07 06:31 UTC, avkviring requested changes

2022-08-07 06:31 UTC, avkviring commented on e2e/Unity/Assets/Tests/User/Store/UserStoreTest.cs
> +            var update = new Update(_clusterConnector, _user);
может Update->UpdateTask? или UpdateAction?

2022-08-07 06:31 UTC, avkviring commented on e2e/Unity/Assets/Tests/User/Store/UserStoreTest.cs
> +            var update = new Update(_clusterConnector, _user);
то есть нужно слово означающие того кто обновляет, имхо

2022-08-07 06:31 UTC, avkviring commented on e2e/Unity/Assets/Tests/User/Store/UserStoreTest.cs
> +            var update = new Update(_clusterConnector, _user);
Updater
https://wikidiff.com/updater/updator

2022-08-07 06:31 UTC, avkviring commented on e2e/Unity/Assets/Tests/User/Store/UserStoreTest.cs
> +            var fetch = new Fetch(_clusterConnector, _user);
Fetcher?

2022-08-07 06:31 UTC, avkviring commented on modules/platform/client/Unity/games.cheetah.platform/Editor/LocalServer/Applications/PlatformApplication.cs
> +        protected PlatformApplication(string name) : base(name) { }
похоже нам надо и тут настроить единые правила автоформатирования

2022-08-07 06:31 UTC, avkviring commented on modules/platform/client/Unity/games.cheetah.platform/Editor/LocalServer/GrpcProxy/GrpcProxyApplication.cs
> +            string config = $@"
а чем var не устроил?

2022-08-07 06:31 UTC, avkviring commented on modules/platform/client/Unity/games.cheetah.platform/Editor/LocalServer/GrpcProxy/GrpcProxyApplication.cs
> +                log_format main $status $request;
А тут почему изменения? табы на пробелы или наоборт?

2022-08-07 06:31 UTC, avkviring commented on modules/user/Store/client/Unity/games.cheetah.user.store/Editor/LocalServer/Registrar.cs
> +            Registry.Register("userstore", CreateApplications());
user.store если придерживаться везде единого правила

2022-08-07 06:31 UTC, avkviring commented on modules/user/Store/client/Unity/games.cheetah.user.store/Editor/LocalServer/UserStoreApplication.cs
> +            ExternalGrpcServices.Add("cheetah.userstore");
тут тоже надо бы user.store

2022-08-07 06:31 UTC, avkviring commented on modules/user/Store/client/Unity/games.cheetah.user.store/Editor/games.cheetah.user.store.editor.asmdef
> +    "rootNamespace": "",
лучше бы не пустой, а по аналогии с другими проектами

2022-08-07 06:31 UTC, avkviring commented on modules/user/Store/client/Unity/games.cheetah.user.store/Editor/games.cheetah.user.store.editor.asmdef
> +    "references": [
ссылки лучше не по GUID делать - а по названиями

2022-08-07 06:31 UTC, avkviring commented on modules/user/Store/proto/user.store.external.proto
> +package cheetah.userstore.external;
user.store

2022-08-08 07:44 UTC, flaamjab commented on modules/platform/client/Unity/games.cheetah.platform/Editor/LocalServer/GrpcProxy/GrpcProxyApplication.cs
> +                log_format main $status $request;
В Unity-пакетах вроде в коде пробелы используются. Но здесь форматирование было непонятное, я поправил.

2022-08-08 07:45 UTC, flaamjab commented on modules/platform/client/Unity/games.cheetah.platform/Editor/LocalServer/GrpcProxy/GrpcProxyApplication.cs
> +            string config = $@"
Ну воевать я за это, конечно, не буду, но в C# предпочтительнее явно указывать тип, если этот тип встроенный.

1. https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008#csharp_style_var_for_built_in_types
2. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types

2022-08-08 07:46 UTC, flaamjab commented on modules/platform/client/Unity/games.cheetah.platform/Editor/LocalServer/GrpcProxy/GrpcProxyApplication.cs
> +            string config = $@"
Вообще можно, наверное, проверки стиля ввести, чтобы такие вопросы не обсуждать.

2022-08-09 01:29 UTC, avkviring commented on modules/platform/client/Unity/games.cheetah.platform/Editor/LocalServer/GrpcProxy/GrpcProxyApplication.cs
> +            string config = $@"
мне в целом без разницы :-) с тебя сделать нам единый стиль + автоформатеры

2022-08-09 01:34 UTC, avkviring submitted a review, later dismissed

2022-08-09 12:14 UTC, flaamjab commented
Closes #45

2022-08-09 12:15 UTC, merged